Repository AlexMarrer/the-rising-sigmas, pull requests merged in 2025-06, with the labels that each got.

#22 Feature/create multi container system
  .gitignore
  Backend/Dockerfile
  Backend/RisingSigma/RisingSigma.API/Program.cs
  Backend/RisingSigma/RisingSigma.API/appsettings.json
  IONIC/Dockerfile
  IONIC/nginx.conf
  IONIC/src/environments/environment.prod.ts
  IONIC/src/environments/environment.ts
  db/Dockerfile
  docker-compose-build.yml
  docker-compose-hub.yml
Labels: enhancement

#25 Feature/create devcontainer
  .devcontainer/Dockerfile.workspace
  .devcontainer/db/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose-dev.yml
  .gitattributes
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  Backend/RisingSigma/RisingSigma.API/Properties/launchSettings.json
  IONIC/package.json
  IONIC/src/environments/environment.prod.ts
  IONIC/src/environments/environment.ts
  IONIC/src/main.ts
  IONIC/src/theme/variables.scss
Labels: enhancement

#31 Feature/27 add drag and drop to table
  .devcontainer/docker-compose-dev.yml
  IONIC/package-lock.json
  IONIC/package.json
  IONIC/src/app/home/home.module.ts
  IONIC/src/app/shared/shared.module.ts
  IONIC/src/app/workout-table/workout-table.component.html
  IONIC/src/app/workout-table/workout-table.component.scss
  IONIC/src/app/workout-table/workout-table.component.ts
  IONIC/src/app/workout-table/workout-table.module.ts
Labels: enhancement

#34 Develop
  .devcontainer/Dockerfile.workspace
  .devcontainer/db/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose-dev.yml
  .gitattributes
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  Backend/Dockerfile
  Backend/RisingSigma/RisingSigma.API/Program.cs
  Backend/RisingSigma/RisingSigma.API/Properties/launchSettings.json
  Backend/RisingSigma/RisingSigma.API/appsettings.json
  INFO.md
  IONIC/Dockerfile
  IONIC/nginx.conf
  IONIC/package-lock.json
  IONIC/package.json
  IONIC/src/app/home/home.module.ts
  IONIC/src/app/settings/settings.page.html
  IONIC/src/app/settings/settings.page.ts
  IONIC/src/app/shared/shared.module.ts
  IONIC/src/app/workout-table/workout-table.component.html
  IONIC/src/app/workout-table/workout-table.component.scss
  IONIC/src/app/workout-table/workout-table.component.ts
  IONIC/src/app/workout-table/workout-table.module.ts
  IONIC/src/assets/i18n/de.json
  IONIC/src/assets/i18n/en.json
  IONIC/src/environments/environment.prod.ts
  IONIC/src/environments/environment.ts
  IONIC/src/main.ts
  IONIC/src/theme/variables.scss
  db/Dockerfile
  docker-compose-build.yml
  docker-compose-hub.yml
Labels: Stage merge

#35 Stage
  .devcontainer/.env
  .devcontainer/Dockerfile.workspace
  .devcontainer/db/Dockerfile
  .devcontainer/docker-compose-dev.yml
  .gitignore
  Backend/Dockerfile
  Backend/RisingSigma/RisingSigma.API/Program.cs
  Backend/RisingSigma/RisingSigma.API/appsettings.json
  INFO.md
  IONIC/Dockerfile
  IONIC/nginx.conf
  IONIC/package-lock.json
  IONIC/package.json
  IONIC/src/app/home/home.module.ts
  IONIC/src/app/settings/settings.page.html
  IONIC/src/app/settings/settings.page.ts
  IONIC/src/app/shared/shared.module.ts
  IONIC/src/app/workout-table/workout-table.component.html
  IONIC/src/app/workout-table/workout-table.component.scss
  IONIC/src/app/workout-table/workout-table.component.ts
  IONIC/src/app/workout-table/workout-table.module.ts
  IONIC/src/assets/i18n/de.json
  IONIC/src/assets/i18n/en.json
  IONIC/src/environments/environment.prod.ts
  IONIC/src/main.ts
  IONIC/src/theme/variables.scss
  db/Dockerfile
  docker-compose-build.yml
  docker-compose-hub.yml
Labels: main merge

#37 Develop
  INFO.md
Labels: Stage merge

#39 Feature/create connection between fe be
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose-dev.yml
  .env.example
  .vscode/launch.json
  Backend/RisingSigma/RisingSigma.API/Controllers/ExerciseController.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/CreateExerciseRequestDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/CreateExerciseResponseDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/CreateExerciseTemplateRequestDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/CreateMuscleGroupRequestDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/ExerciseDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/ExerciseTemplateDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/MuscleGroupDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/UpdateExerciseRequestDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/WeekPlanDto.cs
  Backend/RisingSigma/RisingSigma.API/Extensions/MappingExtensions.cs
  Backend/RisingSigma/RisingSigma.API/Logic/ExerciseLogic.cs
  Backend/RisingSigma/RisingSigma.API/Logic/IExerciseLogic.cs
  Backend/RisingSigma/RisingSigma.API/Logic/IVerificationLogic.cs
  Backend/RisingSigma/RisingSigma.API/Logic/VerificationLogic.cs
  Backend/RisingSigma/RisingSigma.API/Program.cs
  Backend/RisingSigma/RisingSigma.API/Properties/launchSettings.json
  Backend/RisingSigma/RisingSigma.Api.Test/UnitTest1.cs
  Backend/RisingSigma/RisingSigma.Database/ApplicationDbContext.cs
  Backend/RisingSigma/RisingSigma.Database/Entities/Exercise.cs
  Backend/RisingSigma/RisingSigma.Database/Entities/ExerciseTemplate.cs
  Backend/RisingSigma/RisingSigma.Database/Entities/MuscleGroup.cs
  Backend/RisingSigma/RisingSigma.Database/Entities/TrainingPlan.cs
  Backend/RisingSigma/RisingSigma.Database/Entities/User.cs
  Backend/RisingSigma/RisingSigma.Database/Entities/WeekPlan.cs
  INFO.md
  IONIC/src/app/add-exercise-modal/add-exercise-modal.component.html
  IONIC/src/app/add-exercise-modal/add-exercise-modal.component.scss
  IONIC/src/app/add-exercise-modal/add-exercise-modal.component.spec.ts
  IONIC/src/app/add-exercise-modal/add-exercise-modal.component.ts
  IONIC/src/app/header/header.component.scss
  IONIC/src/app/services/exercise.service.ts
  IONIC/src/app/settings/settings.page.html
  IONIC/src/app/settings/settings.page.scss
  IONIC/src/app/settings/settings.page.ts
  IONIC/src/app/workout-table/workout-table.component.html
  IONIC/src/app/workout-table/workout-table.component.scss
  IONIC/src/app/workout-table/workout-table.component.ts
  IONIC/src/app/workout-table/workout-table.module.ts
  IONIC/src/assets/i18n/de.json
  IONIC/src/assets/i18n/en.json
  README.md
  addFeature.md
  docker-compose-build.yml
  docker-compose-hub.yml
Labels: documentation, enhancement

#40 Develop
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose-dev.yml
  .env.example
  .vscode/launch.json
  Backend/RisingSigma/RisingSigma.API/Controllers/ExerciseController.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/CreateExerciseRequestDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/CreateExerciseResponseDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/CreateExerciseTemplateRequestDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/CreateMuscleGroupRequestDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/ExerciseDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/ExerciseTemplateDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/MuscleGroupDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/UpdateExerciseRequestDto.cs
  Backend/RisingSigma/RisingSigma.API/DTOs/WeekPlanDto.cs
  Backend/RisingSigma/RisingSigma.API/Extensions/MappingExtensions.cs
  Backend/RisingSigma/RisingSigma.API/Logic/ExerciseLogic.cs
  Backend/RisingSigma/RisingSigma.API/Logic/IExerciseLogic.cs
  Backend/RisingSigma/RisingSigma.API/Logic/IVerificationLogic.cs
  Backend/RisingSigma/RisingSigma.API/Logic/VerificationLogic.cs
  Backend/RisingSigma/RisingSigma.API/Program.cs
  Backend/RisingSigma/RisingSigma.API/Properties/launchSettings.json
  Backend/RisingSigma/RisingSigma.Api.Test/UnitTest1.cs
  Backend/RisingSigma/RisingSigma.Database/ApplicationDbContext.cs
  Backend/RisingSigma/RisingSigma.Database/Entities/Exercise.cs
  Backend/RisingSigma/RisingSigma.Database/Entities/ExerciseTemplate.cs
  Backend/RisingSigma/RisingSigma.Database/Entities/MuscleGroup.cs
  Backend/RisingSigma/RisingSigma.Database/Entities/TrainingPlan.cs
  Backend/RisingSigma/RisingSigma.Database/Entities/User.cs
  Backend/RisingSigma/RisingSigma.Database/Entities/WeekPlan.cs
  INFO.md
  IONIC/src/app/add-exercise-modal/add-exercise-modal.component.html
  IONIC/src/app/add-exercise-modal/add-exercise-modal.component.scss
  IONIC/src/app/add-exercise-modal/add-exercise-modal.component.spec.ts
  IONIC/src/app/add-exercise-modal/add-exercise-modal.component.ts
  IONIC/src/app/header/header.component.scss
  IONIC/src/app/services/exercise.service.ts
  IONIC/src/app/settings/settings.page.html
  IONIC/src/app/settings/settings.page.scss
  IONIC/src/app/settings/settings.page.ts
  IONIC/src/app/workout-table/workout-table.component.html
  IONIC/src/app/workout-table/workout-table.component.scss
  IONIC/src/app/workout-table/workout-table.component.ts
  IONIC/src/app/workout-table/workout-table.module.ts
  IONIC/src/assets/i18n/de.json
  IONIC/src/assets/i18n/en.json
  README.md
  addFeature.md
  docker-compose-build.yml
  docker-compose-hub.yml
Labels: Stage merge

#42 Hotfix/remove validation logic
  Backend/.dockerignore
  Backend/Dockerfile
  Backend/RisingSigma/RisingSigma.API/Logic/ExerciseLogic.cs
  Backend/RisingSigma/RisingSigma.API/Program.cs
  IONIC/.dockerignore
  IONIC/Dockerfile
Labels: bug
